### ISSUE TITLE
Convert pyinex from google code to github

### ISSUE THREAD

**Issue by sometheycallme** [sometheycallme/levinsky-pyinex#1]
This issue is to track the conversion.

**Comment by sometheycallme** [comment]
@rosslevinsky CC.

**Comment by rosslevinsky** [comment]
Don't spend too much energy on this... We have a bunch of changes to merge
in.

Closed #1 <https://github.com/sometheycallme/levinsky-pyinex/issues/1>.

—
Reply to this email directly or view it on GitHub
<https://github.com/sometheycallme/levinsky-pyinex/issues/1#event-253763399>
.

**Comment by sometheycallme** [comment]
Copy over is done.   Thats about it.
